##############################
# Country definition for USA #
##############################
province = {
  id = 549 # アンカレッジ
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
}
province = { id = 553 supplypool = 1000 } # ジュノー
province = {
  id = 592 # プラッツバーグ
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}
province = {
  id = 595 # コンコード
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}
province = {
  id = 600 # ボストン
  anti_air = 3
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}
province = {
  id = 602 # ニューヨーク
  anti_air = 4
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}
province = {
  id = 606 # ワシントン D.C.
  anti_air = 4
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}
province = { id = 608 anti_air = 2 } # フィラデルフィア
province = {
  id = 614 # ピッツバーグ
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}
province = { id = 615 ic = -2 } # クリーヴランド
province = {
  id = 616 # デトロイト
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}
province = {
  id = 620 # シカゴ
  anti_air = 3
  air_base = { size = 10 current_size = 10 }
}
province = {
  id = 621 # ミルウォーキー
  ic = -2
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}
province = { id = 628 ic = -2 } # コロンバス
province = {
  id = 633 # ノーフォーク
  anti_air = 4
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}
province = {
  id = 637 # シャルロット
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}
province = {
  id = 640 # ルイヴィル
  ic = -2
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}
province = {
  id = 644 # チャールストン
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}
province = {
  id = 648 # ジャクソンヴィル
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}
province = {
  id = 651 # マイアミ
  anti_air = 1
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}
province = { id = 662 supplypool = 100 } # ミッドウェイ諸島
province = {
  id = 663 # パールハーバー
  anti_air = 3
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
  supplypool = 1000
}
province = {
  id = 670 # アトランタ
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}
province = {
  id = 673 # メンフィス
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}
province = {
  id = 678 # ビロクシ
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}
province = {
  id = 684 # リトルロック
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}
province = {
  id = 689 # セントルイス
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}
province = {
  id = 692 # デモイン
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}
province = {
  id = 693 # ミネアポリス
  ic = -2
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}
province = {
  id = 698 # ビズマーク
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}
province = {
  id = 707 # デンバー
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}
province = {
  id = 713 # オクラホマシティ
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}
province = {
  id = 716 # ヒューストン
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}
province = {
  id = 725 # サンタフェ
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}
province = {
  id = 730 # フェニックス
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}
province = {
  id = 733 # ソルトレイクシティ
  anti_air = 1
  air_base = { size = 10 current_size = 10 }
}
province = {
  id = 748 # コーパスクリスティ
  anti_air = 1
  air_base = { size = 6 current_size = 6 }
  naval_base = { size = 8 current_size = 8 }
}
province = {
  id = 761 # サンディエゴ
  anti_air = 1
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}
province = {
  id = 762 # ロサンゼルス
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 8 current_size = 8 }
}
province = {
  id = 764 # サクラメント
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}
province = {
  id = 765 # サンフランシスコ
  anti_air = 3
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}
province = {
  id = 780 # シアトル
  anti_air = 1
  air_base = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}
province = {
  id = 783 # ポートランド
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}
province = {
  id = 789 # オマハ
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}
province = {
  id = 793 # タルサ
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}
province = {
  id = 889 # コロン
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
  supplypool = 100
}
province = { id = 895 supplypool = 50 } # プエルトリコ
province = { id = 1408 supplypool = 500 } # アッツ島
province = {
  id = 1624 # グアム
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
  supplypool = 100
}
province = {
  id = 1737 # マニラ
  anti_air = 2
  air_base = { size = 1 current_size = 1 }
  naval_base = { size = 8 current_size = 8 }
}
province = {
  id = 1739 # クラークフィールド
  anti_air = 4
  air_base = { size = 5 current_size = 5 }
  naval_base = { size = 2 current_size = 2 }
}
province = { id = 1756 supplypool = 50 } # サモア
province = { id = 1762 supplypool = 1 } # フェニックス島
province = { id = 1765 supplypool = 50 } # パルミラ
province = { id = 1766 supplypool = 1 } # ジョンソン島
province = {
  id = 1786 # ウェーク島
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
  supplypool = 100
}

#####################
# Country main data #
#####################

country = {
  tag                = USA
  capital            = 606 # ワシントン D.C.
  manpower           = 40
  peacetime_ic_mod       = 0.25
  # Resource Reserves
  energy         = 1000
  metal          = 1000
  rare_materials = 500
  oil            = 500
  supplies       = 500
  money          = 100
  transports     = 540
  escorts        = 53
  tc_mod = 1.1000	#1.0+0.1
  ai_settings	= { flags = {
  	Panama_Canel = 1
  } }
  diplomacy = {
    relation = {
      tag        = ARG
      value      = 75
      guaranteed = { year = 1935 month = december day = 30 }
    }
    relation = { tag = AST value = 125 }
    relation = { tag = BEL value = 75 }
    relation = { tag = BHU value = 100 }
    relation = {
      tag        = BOL
      value      = 85
      guaranteed = { year = 1935 month = december day = 30 }
    }
    relation = {
      tag        = BRA
      value      = 120
      guaranteed = { year = 1935 month = december day = 30 }
    }
    relation = {
      tag        = CAN
      value      = 175
      guaranteed = { year = 1935 month = december day = 30 }
    }
    relation = {
      tag        = CHL
      value      = 100
      guaranteed = { year = 1935 month = december day = 30 }
    }
    relation = {
      tag        = COL
      value      = 75
      guaranteed = { year = 1935 month = december day = 30 }
    }
    relation = {
      tag        = COS
      value      = 100
      guaranteed = { year = 1935 month = december day = 30 }
    }
    relation = {
      tag        = CUB
      value      = 200
      access     = yes
      guaranteed = { year = 1935 month = december day = 30 }
    }
    relation = { tag = DEN value = 75 }
    relation = {
      tag        = DOM
      value      = 125
      guaranteed = { year = 1935 month = december day = 30 }
    }
    relation = {
      tag        = ECU
      value      = 75
      guaranteed = { year = 1935 month = december day = 30 }
    }
    relation = { tag = ENG value = 150 }
    relation = { tag = FIN value = 90 }
    relation = { tag = FRA value = 65 }
    relation = { tag = GER value = -10 }
    relation = {
      tag        = GUA
      value      = 125
      guaranteed = { year = 1935 month = december day = 30 }
    }
    relation = {
      tag        = HAI
      value      = 100
      guaranteed = { year = 1935 month = december day = 30 }
    }
    relation = { tag = HOL value = 70 }
    relation = {
      tag        = HON
      value      = 100
      guaranteed = { year = 1935 month = december day = 30 }
    }
    relation = { tag = IRE value = 75 }
    relation = { tag = IRQ value = 120 }
    relation = { tag = JAP value = 15 }
    relation = { tag = LIB value = 200 access = yes }
    relation = { tag = MAN value = 1 }
    relation = {
      tag        = MEX
      value      = 125
      guaranteed = { year = 1935 month = december day = 30 }
    }
    relation = { tag = NEP value = 100 }
    relation = {
      tag        = NIC
      value      = 100
      guaranteed = { year = 1935 month = december day = 30 }
    }
    relation = { tag = NOR value = 75 }
    relation = { tag = NZL value = 125 }
    relation = { tag = OMN value = 100 }
    relation = {
      tag        = PAN
      value      = 175
      guaranteed = { year = 1935 month = december day = 30 }
    }
    relation = {
      tag        = PAR
      value      = 75
      guaranteed = { year = 1935 month = december day = 30 }
    }
    relation = { tag = PHI value = 200 access = yes }
    relation = {
      tag        = PRU
      value      = 75
      guaranteed = { year = 1935 month = december day = 30 }
    }
    relation = { tag = SAF value = 125 }
    relation = {
      tag        = SAL
      value      = 100
      guaranteed = { year = 1935 month = december day = 30 }
    }
    relation = { tag = SOV value = 35 }
    relation = {
      tag        = SCH
      value      = 1
      guaranteed = { year = 1935 month = december day = 30 }
    }
    relation = { tag = SWE value = 75 }
    relation = {
      tag        = URU
      value      = 100
      guaranteed = { year = 1935 month = december day = 30 }
    }
    relation = {
      tag        = VEN
      value      = 125
      guaranteed = { year = 1935 month = december day = 30 }
    }
    relation = { tag = YEM value = 100 }
  }
  SpyInfo                = { country = "USA" NumberOfSpies = 10 }
  SpyInfo                = { country = "ENG" NumberOfSpies = 6 }
  SpyInfo                = { country = "FRA" NumberOfSpies = 3 }
  SpyInfo                = { country = "SOV" NumberOfSpies = 3 }
  SpyInfo                = { country = "AST" NumberOfSpies = 3 }
  SpyInfo                = { country = "VEN" NumberOfSpies = 8 }
  SpyInfo                = { country = "SPR" NumberOfSpies = 8 }
  SpyInfo                = { country = "POL" NumberOfSpies = 3 }
  SpyInfo                = { country = "PAN" NumberOfSpies = 5 }
  SpyInfo                = { country = "ECU" NumberOfSpies = 3 }
  SpyInfo                = { country = "BOL" NumberOfSpies = 6 }
  SpyInfo                = { country = "CAN" NumberOfSpies = 8 }
  SpyInfo                = { country = "CUB" NumberOfSpies = 9 }
  SpyInfo                = { country = "SCH" NumberOfSpies = 6 }
  SpyInfo                = { country = "DOM" NumberOfSpies = 8 }
  SpyInfo                = { country = "GUA" NumberOfSpies = 6 }
  SpyInfo                = { country = "HAI" NumberOfSpies = 6 }
  SpyInfo                = { country = "ARG" NumberOfSpies = 3 }
  SpyInfo                = { country = "GER" NumberOfSpies = 3 }
  SpyInfo                = { country = "NIC" NumberOfSpies = 3 }
  SpyInfo                = { country = "SAL" NumberOfSpies = 3 }
  SpyInfo                = { country = "PRU" NumberOfSpies = 3 }
  SpyInfo                = { country = "JAP" NumberOfSpies = 3 }
  SpyInfo                = { country = "PHI" NumberOfSpies = 8 }
  SpyInfo                = { country = "CHL" NumberOfSpies = 3 }
  SpyInfo                = { country = "ITA" NumberOfSpies = 3 }
  SpyInfo                = { country = "CHI" NumberOfSpies = 3 }
  SpyInfo                = { country = "MEX" NumberOfSpies = 9 }

  nationalprovinces      = { 651 650 649 648 677 676 672 646 647 669 670 644 645 634 635 636 637 643 633 632 631 638 639 606 607 605 604 603 612 602 598 593 592 608 609 610 611 594 597 595 596 582 583 599 600 601 613 614 629 630 640 641 642 671 673 674 675 678 679 615 628 617 616 618 619 627 680 681 682 683 684 685 686 687 688 689 626 625 620 621 624 623 622 690 691 692 693 694 695 696 697 698 699 787 788 789 790 791 792 793 710 711 712 713 714 715 716 717 719 720 721 748 722 723 724 725 727 728 729 730 731 732 733 706 707 708 709 705 704 703 702 701 700 775 774 770 771 772 773 776 777 779 780 781 782 783 784 785 786 778 769 768 734 736 735 767 761 762 763 764 765 766 553 551 550 549 548 547 546 545 544 543 542 718 726 746 1408 895 }
  ownedprovinces         = { 651 650 649 648 677 676 672 646 647 669 670 644 645 634 635 636 637 643 633 632 631 638 639 606 607 605 604 603 612 602 598 593 592 608 609 610 611 594 597 595 596 582 583 599 600 601 613 614 629 630 640 641 642 671 673 674 675 678 679 615 628 617 616 618 619 627 680 681 682 683 684 685 686 687 688 689 626 625 620 621 624 623 622 690 691 692 693 694 695 696 697 698 699 787 788 789 790 791 792 793 710 711 712 713 714 715 716 717 719 720 721 748 722 723 724 725 727 728 729 730 731 732 733 706 707 708 709 705 704 703 702 701 700 775 774 770 771 772 773 776 777 779 780 781 782 783 784 785 786 778 769 768 734 736 735 767 761 762 763 764 765 766 553 551 550 549 548 547 546 545 544 543 542 718 726 746 895 889 658 659 660 661 662 663 1756 1766 1762 1786 1624 1408 1764 1765 1735 1736 1737 1738 1739 1740 1741 1742 1743 1744 1745 1746 1747 1748 1749 1750 }
  controlledprovinces    = { 651 650 649 648 677 676 672 646 647 669 670 644 645 634 635 636 637 643 633 632 631 638 639 606 607 605 604 603 612 602 598 593 592 608 609 610 611 594 597 595 596 582 583 599 600 601 613 614 629 630 640 641 642 671 673 674 675 678 679 615 628 617 616 618 619 627 680 681 682 683 684 685 686 687 688 689 626 625 620 621 624 623 622 690 691 692 693 694 695 696 697 698 699 787 788 789 790 791 792 793 710 711 712 713 714 715 716 717 719 720 721 748 722 723 724 725 727 728 729 730 731 732 733 706 707 708 709 705 704 703 702 701 700 775 774 770 771 772 773 776 777 779 780 781 782 783 784 785 786 778 769 768 734 736 735 767 761 762 763 764 765 766 553 551 550 549 548 547 546 545 544 543 542 718 726 746 895 889 658 659 660 661 662 663 1756 1766 1762 1786 1624 1408 1764 1765 1735 1736 1737 1738 1739 1740 1741 1742 1743 1744 1745 1746 1747 1748 1749 1750 }
  claimedprovinces       = { 889 }

  techapps               = { 1010 1190 1200 12100 1310 14000 2010 2150 2290 2300 2310 2450 2460 2510 3010 3020 3070 3080 3130 3140 3150 3190 3200 3210 3250 3260 3270 3320 3330 3340 3400 3410 3470 3420 3480 4010 4020 4120 4130 4190 4220 4250 4260 5010 5020 5050 5060 5080 5090 5310 5320 5470 5480 6010 6020 8010 8020 8030 8040 8050 8060 8090 8100 9010 9020 9030 9140 1150 5030 }

  policy = {
    date              = { year = 0 month = january day = 0 }
    democratic        = 10
    political_left    = 6
    freedom           = 10
    #free_market       = 10
    free_market       = 4
    professional_army = 1
    defense_lobby     = 1
    interventionism   = 1
  }
  headofstate            = { type = 9 id = 6001 } # フランクリン・D・ルーズベルト
  headofgovernment       = { type = 9 id = 6002 } # ジョン・ナンス・ガーナー
  foreignminister        = { type = 9 id = 6003 } # コーデル・ハル
  armamentminister       = { type = 9 id = 6077 } # ヘンリー・モーゲンソー
  ministerofsecurity     = { type = 9 id = 6005 } # J・エドガー・フーバー
  ministerofintelligence = { type = 9 id = 6006 } # ウィリアム・F・フリードマン
  chiefofstaff           = { type = 9 id = 6007 } # マーリン・クレイグ
  chiefofarmy            = { type = 9 id = 6008 } # マーリン・クレイグ
  chiefofnavy            = { type = 9 id = 6158 } # ウィリアム・H・スタンドレー
  chiefofair             = { type = 9 id = 6010 } # オスカー・ウェストーヴァー

  landunit = {
    id       = { type = 14800 id = 3 }
    name     = "合衆国第1軍団"
    location = 603
    division = {
      id             = { type = 14800 id = 4 }
      name           = "第1「ビッグ・レッド・ワン」師団"
      type           = infantry
    }
  }
  landunit = {
    id       = { type = 14800 id = 5 }
    name     = "合衆国第2軍団"
    location = 606
    division = {
      id             = { type = 14800 id = 6 }
      name           = "第2「インディアンヘッド」師団"
      type           = infantry
    }
  }
  landunit = {
    id       = { type = 14800 id = 7 }
    name     = "合衆国第3軍団"
    location = 762
    division = {
      id             = { type = 14800 id = 8 }
      name           = "第3「ロック・オブ・ザ・マリーン」師団"
      type           = infantry
    }
  }
  landunit = {
    id       = { type = 14800 id = 9 }
    name     = "合衆国騎兵部隊"
    location = 707
    division = {
      id             = { type = 14800 id = 10 }
      name           = "第1騎兵「ザ・ファースト・チーム」師団"
      type           = cavalry
    }
  }
  landunit = {
    id       = { type = 14800 id = 11 }
    name     = "フィリピン軍"
    location = 1737
    division = {
      id             = { type = 14800 id = 12 }
      name           = "フィリピン師団"
      type           = infantry
      locked         = yes
    }
  }
  landunit = {
    id       = { type = 14800 id = 160 }
    name     = "パナマ運河部隊"
    location = 889
    division = {
      id             = { type = 14800 id = 161 }
      name           = "パナマ運河守備隊"
      type           = garrison
      model          = 0
      extra          = artillery
      locked         = yes
    }
  }

  navalunit = {
    id       = { type = 14800 id = 26 }
    name     = "USN 第1戦艦隊"
    location = 761
    base     = 761
    division = {
      id             = { type = 14800 id = 27 }
      name           = "USS レキシントン"
      type           = carrier
      model          = 1
      extra1         = cag
      brigade_model1 = 2
    }
    division = {
      id             = { type = 14800 id = 28 }
      name           = "USS ネヴァダ"
      type           = battleship
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 29 }
      name           = "USS アリゾナ"
      type           = battleship
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 30 }
      name           = "USS ペンシルヴァニア"
      type           = battleship
      model          = 1
    }
  }
  navalunit = {
    id       = { type = 14800 id = 31 }
    name     = "USN 第2戦艦隊"
    location = 761
    base     = 761
    division = {
      id             = { type = 14800 id = 32 }
      name           = "USS サラトガ"
      type           = carrier
      model          = 1
      extra1         = cag
      brigade_model1 = 2
    }
    division = {
      id             = { type = 14800 id = 33 }
      name           = "USS オクラホマ"
      type           = battleship
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 34 }
      name           = "USS テネシー"
      type           = battleship
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 35 }
      name           = "USS カリフォルニア"
      type           = battleship
      model          = 1
    }
  }
  navalunit = {
    id       = { type = 14800 id = 36 }
    name     = "USN 第4戦艦隊"
    location = 761
    base     = 761
    division = {
      id             = { type = 14800 id = 37 }
      name           = "USS コロラド"
      type           = battleship
      model          = 2
    }
    division = {
      id             = { type = 14800 id = 38 }
      name           = "USS ウェストヴァージニア"
      type           = battleship
      model          = 2
    }
    division = {
      id             = { type = 14800 id = 39 }
      name           = "USS メリーランド"
      type           = battleship
      model          = 2
    }
  }
  navalunit = {
    id       = { type = 14800 id = 40 }
    name     = "USN 第3巡洋艦隊"
    location = 761
    base     = 761
    division = {
      id             = { type = 14800 id = 41 }
      name           = "USS リットモンド"
      type           = light_cruiser
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 42 }
      name           = "USS トレントン"
      type           = light_cruiser
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 43 }
      name           = "USS コンコード"
      type           = light_cruiser
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 44 }
      name           = "USS ローリー"
      type           = light_cruiser
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 45 }
      name           = "USS デトロイト"
      type           = light_cruiser
      model          = 1
    }
  }
  navalunit = {
    id       = { type = 14800 id = 46 }
    name     = "USN 第4巡洋艦隊"
    location = 761
    base     = 761
    division = {
      id             = { type = 14800 id = 47 }
      name           = "USS ペンサコーラ"
      type           = heavy_cruiser
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 48 }
      name           = "USS ソルトレイクシティー"
      type           = heavy_cruiser
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 49 }
      name           = "USS シカゴ"
      type           = heavy_cruiser
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 50 }
      name           = "USS インディアナアポリス"
      type           = heavy_cruiser
      model          = 1
    }
  }
  navalunit = {
    id       = { type = 14800 id = 51 }
    name     = "USN 第5巡洋艦隊"
    location = 761
    base     = 761
    division = {
      id             = { type = 14800 id = 52 }
      name           = "USS ノーサンプトン"
      type           = heavy_cruiser
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 53 }
      name           = "USS チェスター"
      type           = heavy_cruiser
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 54 }
      name           = "USS ルイヴィル"
      type           = heavy_cruiser
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 55 }
      name           = "USS ポートランド"
      type           = heavy_cruiser
      model          = 1
    }
  }
  navalunit = {
    id       = { type = 14800 id = 56 }
    name     = "USN 第6巡洋艦隊"
    location = 761
    base     = 761
    division = {
      id             = { type = 14800 id = 57 }
      name           = "USS ニューオリンズ"
      type           = heavy_cruiser
      model          = 2
    }
    division = {
      id             = { type = 14800 id = 58 }
      name           = "USS アストリア"
      type           = heavy_cruiser
      model          = 2
    }
    division = {
      id             = { type = 14800 id = 59 }
      name           = "USS ミネアポリス"
      type           = heavy_cruiser
      model          = 2
    }
    division = {
      id             = { type = 14800 id = 60 }
      name           = "USS サンフランシスコ"
      type           = heavy_cruiser
      model          = 2
    }
  }
  navalunit = {
    id       = { type = 14800 id = 61 }
    name     = "太平洋駆逐艦隊"
    location = 761
    base     = 761
    division = {
      id             = { type = 14800 id = 62 }
      name           = "USS ハルバート"
      type           = destroyer
      model          = 0
    }
    division = {
      id             = { type = 14800 id = 63 }
      name           = "USS ノア"
      type           = destroyer
      model          = 0
    }
    division = {
      id             = { type = 14800 id = 64 }
      name           = "USS ウィリアム・B・プレストン"
      type           = destroyer
      model          = 0
    }
  }
  navalunit = {
    id       = { type = 14800 id = 74 }
    name     = "太平洋潜水艦隊"
    location = 761
    base     = 761
    division = {
      id             = { type = 14800 id = 75 }
      name           = "第1潜水隊"
      type           = submarine
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 76 }
      name           = "第2潜水隊"
      type           = submarine
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 77 }
      name           = "第3潜水隊"
      type           = submarine
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 78 }
      name           = "第4潜水隊"
      type           = submarine
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 79 }
      name           = "第5潜水隊"
      type           = submarine
      model          = 0
    }
    division = {
      id             = { type = 14800 id = 80 }
      name           = "第6潜水隊"
      type           = submarine
      model          = 0
    }
  }
  navalunit = {
    id       = { type = 14800 id = 81 }
    name     = "アジア艦隊"
    location = 1737
    base     = 1737
    division = {
      id             = { type = 14800 id = 82 }
      name           = "USS プレブル"
      type           = destroyer
      model          = 0
    }
    division = {
      id             = { type = 14800 id = 83 }
      name           = "USS シカード"
      type           = destroyer
      model          = 0
    }
    division = {
      id             = { type = 14800 id = 84 }
      name           = "USS プルーイット"
      type           = destroyer
      model          = 0
    }
    division = {
      id             = { type = 14800 id = 179 }
      name           = "USS ファラガット"
      type           = destroyer
      model          = 0
    }
    division = {
      id             = { type = 14800 id = 180 }
      name           = "USS デューイ"
      type           = destroyer
      model          = 0
    }
    division = {
      id             = { type = 14800 id = 85 }
      name           = "第7潜水隊"
      type           = submarine
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 86 }
      name           = "第8潜水隊"
      type           = submarine
      model          = 1
    }
  }
  navalunit = {
    id       = { type = 14800 id = 87 }
    name     = "USN 第2潜水艦隊"
    location = 1737
    base     = 1737
    division = {
      id             = { type = 14800 id = 88 }
      name           = "第9潜水隊"
      type           = submarine
      model          = 1
    }
  }
  navalunit = {
    id       = { type = 14800 id = 89 }
    name     = "USN シアトル艦隊"
    location = 780
    base     = 780
    division = {
      id             = { type = 14800 id = 90 }
      name           = "USS マーブルヘッド"
      type           = light_cruiser
      model          = 1
      strength       = 100
    }
    division = {
      id             = { type = 14800 id = 91 }
      name           = "USS ハル"
      type           = destroyer
      model          = 0
    }
    division = {
      id             = { type = 14800 id = 189 }
      name           = "USS マクドノー"
      type           = destroyer
      model          = 0
    }
  }
  navalunit = {
    id       = { type = 14800 id = 92 }
    name     = "USN コロンビア艦隊"
    location = 780
    base     = 780
    division = {
      id             = { type = 14800 id = 93 }
      name           = "USS ヒューストン"
      type           = heavy_cruiser
      model          = 1
      strength       = 100
    }
    division = {
      id             = { type = 14800 id = 192 }
      name           = "USS ウォーデン"
      type           = destroyer
      model          = 0
    }
    division = {
      id             = { type = 14800 id = 94 }
      name           = "第10潜水隊"
      type           = submarine
      model          = 1
    }
  }
  navalunit = {
    id       = { type = 14800 id = 95 }
    name     = "USN カリブ艦隊"
    location = 889
    base     = 889
    division = {
      id             = { type = 14800 id = 96 }
      name           = "USS デイル"
      type           = destroyer
      model          = 0
    }
    division = {
      id             = { type = 14800 id = 97 }
      name           = "第11潜水隊"
      type           = submarine
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 190 }
      name           = "USS モナハン"
      type           = destroyer
      model          = 0
    }
    division = {
      id             = { type = 14800 id = 191 }
      name           = "USS エールウィン"
      type           = destroyer
      model          = 0
    }
  }
  navalunit = {
    id       = { type = 14800 id = 98 }
    name     = "USN 第3戦闘艦隊"
    location = 633
    base     = 633
    division = {
      id             = { type = 14800 id = 99 }
      name           = "USS ニューメキシコ"
      type           = battleship
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 100 }
      name           = "USS ミシシッピー"
      type           = battleship
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 101 }
      name           = "USS アイダホ"
      type           = battleship
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 193 }
      name           = "USS ポーター"
      type           = destroyer
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 194 }
      name           = "USS セルフリッジ"
      type           = destroyer
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 195 }
      name           = "USS マグドゥガル"
      type           = destroyer
      model          = 1
    }
  }
  navalunit = {
    id       = { type = 14800 id = 102 }
    name     = "USN 第5戦闘艦隊"
    location = 633
    base     = 633
    division = {
      id             = { type = 14800 id = 103 }
      name           = "USS アーカンソー"
      type           = battleship
      model          = 0
    }
    division = {
      id             = { type = 14800 id = 104 }
      name           = "USS ニューヨーク"
      type           = battleship
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 105 }
      name           = "USS テキサス"
      type           = battleship
      model          = 1
    }
  }
  navalunit = {
    id       = { type = 14800 id = 106 }
    name     = "USN 第2巡洋艦隊"
    location = 633
    base     = 633
    division = {
      id             = { type = 14800 id = 107 }
      name           = "USS オマハ"
      type           = light_cruiser
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 108 }
      name           = "USS ミルウォーキー"
      type           = light_cruiser
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 109 }
      name           = "USS シンシナティー"
      type           = light_cruiser
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 110 }
      name           = "USS メンフィス"
      type           = light_cruiser
      model          = 1
    }
  }
  navalunit = {
    id       = { type = 14800 id = 111 }
    name     = "USN 第7巡洋艦隊"
    location = 633
    base     = 633
    division = {
      id             = { type = 14800 id = 112 }
      name           = "USS オーガスタ"
      type           = heavy_cruiser
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 113 }
      name           = "USS タスカルーサ"
      type           = heavy_cruiser
      model          = 2
    }
  }
  navalunit = {
    id       = { type = 14800 id = 114 }
    name     = "USS レンジャー任務部隊"
    location = 633
    base     = 633
    division = {
      id             = { type = 14800 id = 115 }
      name           = "USS レンジャー"
      type           = carrier
      model          = 2
      extra1         = cag
      brigade_model1 = 2
    }
    division = {
      id             = { type = 14800 id = 116 }
      name           = "USS ウィンスロー"
      type           = destroyer
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 117 }
      name           = "USS クラーク"
      type           = destroyer
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 118 }
      name           = "USS モフェット"
      type           = destroyer
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 119 }
      name           = "USS バルチ"
      type           = destroyer
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 120 }
      name           = "USS マハン"
      type           = destroyer
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 121 }
      name           = "USS カミングス"
      type           = destroyer
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 172 }
      name           = "USS ドレイトン"
      type           = destroyer
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 173 }
      name           = "USS ラムソン"
      type           = destroyer
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 174 }
      name           = "USS フラッサー"
      type           = destroyer
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 175 }
      name           = "USS リード"
      type           = destroyer
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 176 }
      name           = "USS ケース"
      type           = destroyer
      model          = 1
    }
  }
  navalunit = {
    id       = { type = 14800 id = 122 }
    name     = "大西洋潜水艦隊"
    location = 633
    base     = 633
    division = {
      id             = { type = 14800 id = 123 }
      name           = "第12潜水隊"
      type           = submarine
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 124 }
      name           = "第13潜水隊"
      type           = submarine
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 125 }
      name           = "第14潜水隊"
      type           = submarine
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 126 }
      name           = "第15潜水隊"
      type           = submarine
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 127 }
      name           = "第16潜水隊"
      type           = submarine
      model          = 2
    }
    division = {
      id             = { type = 14800 id = 128 }
      name           = "第17潜水隊"
      type           = submarine
      model          = 2
    }
  }
  navalunit = {
    id       = { type = 14800 id = 133 }
    name     = "大西洋輸送艦隊"
    location = 633
    base     = 633
    division = {
      id             = { type = 14800 id = 134 }
      name           = "アブナー・ダブルディー隊"
      type           = transport
    }
    division = {
      id             = { type = 14800 id = 135 }
      name           = "ブリガム・ヤング隊"
      type           = transport
    }
    division = {
      id             = { type = 14800 id = 136 }
      name           = "ウィリアム B.トラヴィス隊"
      type           = transport
    }
    division = {
      id             = { type = 14800 id = 137 }
      name           = "ピーター・スタイヴェサント隊"
      type           = transport
    }
    division = {
      id             = { type = 14800 id = 138 }
      name           = "ヘンリー・L・ベニング隊"
      type           = transport
    }
    division = {
      id             = { type = 14800 id = 139 }
      name           = "カシミール・プラスキー隊"
      type           = transport
    }
    division = {
      id             = { type = 14800 id = 140 }
      name           = "サム・ヒューストン隊"
      type           = transport
    }
    division = {
      id             = { type = 14800 id = 141 }
      name           = "フランシス・スコット・キー隊"
      type           = transport
    }
    division = {
      id             = { type = 14800 id = 142 }
      name           = "ウォルター・リード隊"
      type           = transport
    }
    division = {
      id             = { type = 14800 id = 143 }
      name           = "ドリー・マディソン隊"
      type           = transport
    }
    division = {
      id             = { type = 14800 id = 144 }
      name           = "フレデリック・ダグラス隊"
      type           = transport
    }
    division = {
      id             = { type = 14800 id = 145 }
      name           = "クララ・バートン隊"
      type           = transport
    }
  }
  navalunit = {
    id       = { type = 14800 id = 146 }
    name     = "大平洋輸送艦隊"
    location = 761
    base     = 761
    division = {
      id             = { type = 14800 id = 147 }
      name           = "チャールズ・グッドイヤー隊"
      type           = transport
    }
    division = {
      id             = { type = 14800 id = 148 }
      name           = "アンソニー・ウェイン隊"
      type           = transport
    }
    division = {
      id             = { type = 14800 id = 149 }
      name           = "ジョン・ハンコック隊"
      type           = transport
    }
    division = {
      id             = { type = 14800 id = 150 }
      name           = "サミュエル・デクスター隊"
      type           = transport
    }
    division = {
      id             = { type = 14800 id = 151 }
      name           = "スティーヴン・C.クレイン隊"
      type           = transport
    }
    division = {
      id             = { type = 14800 id = 152 }
      name           = "ウィリアム・マッキンリー隊"
      type           = transport
    }
    division = {
      id             = { type = 14800 id = 153 }
      name           = "ジョージ・A.カスター隊"
      type           = transport
    }
    division = {
      id             = { type = 14800 id = 154 }
      name           = "オーガスト・ベルモント隊"
      type           = transport
    }
    division = {
      id             = { type = 14800 id = 156 }
      name           = "エミリー・ディキンソン隊"
      type           = transport
    }
    division = {
      id             = { type = 14800 id = 157 }
      name           = "モリー・ピッチャー隊"
      type           = transport
    }
    division = {
      id             = { type = 14800 id = 158 }
      name           = "アントニン・ドヴォラク隊"
      type           = transport
    }
    division = {
      id             = { type = 14800 id = 159 }
      name           = "J.E.B.スチュワート隊"
      type           = transport
    }
  }

  airunit = { 
    id       = { type = 14800 id = 13 }
    name     = "USAAF 第1戦闘航空団"
    location = 761
    base     = 761
    division = {
      id             = { type = 14800 id = 14 }
      name           = "USAAF 第6戦闘航空団"
      type           = interceptor
      model          = 1
    }
  }
  airunit = { 
    id       = { type = 14800 id = 15 }
    name     = "USAAF 第2爆撃航空団"
    location = 780
    base     = 780
    division = {
      id             = { type = 14800 id = 16 }
      name           = "USAAF 第2戦略爆撃航空団"
      type           = strategic_bomber
      model          = 0
    }
  }
  airunit = { 
    id       = { type = 14800 id = 17 }
    name     = "USAAF 第1爆撃航空団"
    location = 606
    base     = 606
    division = {
      id             = { type = 14800 id = 18 }
      name           = "USAAF 第1急降下爆撃航空団"
      type           = tactical_bomber
      model          = 0
    }
  }
  airunit = { 
    id       = { type = 14800 id = 19 }
    name     = "USAAF 第5爆撃航空団"
    location = 889
    base     = 889
    division = {
      id             = { type = 14800 id = 20 }
      name           = "USAAF 第5戦術爆撃航空団"
      type           = tactical_bomber
      model          = 0
    }
  }
  airunit = { 
    id       = { type = 14800 id = 21 }
    name     = "USAAF 第7爆撃航空団"
    location = 780
    base     = 780
    division = {
      id             = { type = 14800 id = 22 }
      name           = "USAAF 第1戦術爆撃航空団"
      type           = tactical_bomber
      model          = 0
    }
  }
  airunit = { 
    id       = { type = 14800 id = 23 }
    name     = "合衆国空軍"
    location = 602
    base     = 602
    division = {
      id             = { type = 14800 id = 24 }
      name           = "USAAF 第9戦闘航空団"
      type           = interceptor
      model          = 1
    }
    division = {
      id             = { type = 14800 id = 25 }
      name           = "USAAF 第2戦術爆撃航空団"
      type           = tactical_bomber
      model          = 0
    }
  }

  division_development = {
    id             = { type = 14800 id = 500 }
    name           = "USS ヨークタウン"
    type           = carrier
    model          = 2
    cost           = 4.8
    date           = { year = 1936 month = september day = 30 }
  }
  brigade_development =
  { id    = { type = 14800 id = 205 }
    name  = "USS ヨークタウン空母航空隊"
    cost  = 1.3
    date  = { year = 1936 month = september day = 30 }
    type  = cag
    model = 2
  }
  division_development =
  { name  = "USS クインシー"
    type  = heavy_cruiser
    model = 2
    cost  = 4.8
    id    = { type = 14800 id = 501 }
    date  = { year = 1935 month = december day = 9 }
  }
  division_development =
  { name  = "USS フェルプス"
    type  = destroyer
    model = 1
    cost  = 1.6
    id    = { type = 14800 id = 502 }
    date  = { year = 1935 month = july day = 17 }
  }
  division_development =
  { name  = "USS カニンガム"
    type  = destroyer
    model = 1
    cost  = 1.6
    id    = { type = 14800 id = 503 }
    date  = { year = 1935 month = september day = 14 }
  }
  division_development =
  { name  = "第18潜水隊"
    type  = submarine
    model = 2
    cost  = 1.6
    id    = { type = 14800 id = 504 }
    date  = { year = 1935 month = november day = 1 }
  }
  
    landdivision = { 
    	dormant = yes 
    	id = { type = 14800 id = 65 } 
    	name = "第24「ヴィクトリー」師団"  
    	type = infantry 
    	model = 5
    	extra = police 
    	brigade_model = 0
    	locked = yes 
    } 
    landdivision = { 
    	dormant = yes 
    	id = { type = 14800 id = 66 } 
    	name = "第1騎兵「ザ・ファースト・チーム」師団"  
    	type = cavalry 
    	model = 3
    	locked = yes 
    } 
    landdivision = { 
    	dormant = yes 
    	id = { type = 14800 id = 67 } 
    	name = "第11空挺「ジ・エンジェルス」師団"  
    	type = paratrooper 
    	model = 3
    	locked = yes 
    } 
}
